# 全局日志默认级别
# Must be one of ("trace", "debug", "info", "warn", "error", "off").
org.slf4j.simpleLogger.defaultLogLevel=error
# 显示时间
org.slf4j.simpleLogger.showDateTime=true
# 时间格式
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss
# 显示线程名
org.slf4j.simpleLogger.showThreadName=true
# 显示线程ID
org.slf4j.simpleLogger.showThreadId=true
# 显示包路径
org.slf4j.simpleLogger.showLogName=true
# 显示短的包路径
org.slf4j.simpleLogger.showShortLogName=false
# 是否在日志级别前后添加方括号
org.slf4j.simpleLogger.levelInBrackets=true
